### ISSUE TITLE
adminstrators van een groep mogen geen groepsinformatie bewerken

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/grouphub#12]
Dus ze mogen niet:
- de naam aanpassen
- de beschrijving veranderen
- het type groep veranderen

- de groep verwijderen

Ze mogen wel:
- leden toevoegen/verwijderen

ZIe de rollen tabel in de documentatie voor het gewenste gedrag:
https://wiki.surfnet.nl/display/Grouphub/Rollen

**Comment by Tjeerd** [comment]
De permissies per rol zijn aangepast
