### ISSUE TITLE
zoeken naar members (met spaties) is nog niet goed

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/grouphub#13]
part 1: 
het zoeken naar members via 'add members' lukt alleen met 1 spatie. Zoeken naar 'cas de wit' met 2 spaties werkt niet

part 2:
het zoeken naar members via 'group members' lukt helemaal niet bij gebruik van een spatie (als part 1 is opgelost, kan die hier hergebruikt worden)

**Comment by Tjeerd** [comment]
Aanpassingen doorgevoerd zodat het zoeken met spaties iets slimmer is geworden.
