### ISSUE TITLE
LDAP Sync - Synchronisatie van users stopt bij user met ongeldig e-mailadres

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/grouphub#131]
Bij het draaien van de sync tussen grouphub en ldap bij inholland is er een probleem. Ik zie updates van alle users langskomen. Dit is sowieso nieuw. Normaal werden users niet telkens geupdate. Maar het echte probleem is dat de update stopt bij een specifieke user met de melding dat de update niet gedaan kan worden op de api. Zie screenshot 1:

![error-inholland](https://cloud.githubusercontent.com/assets/1597455/23405126/0d9641a8-fdb9-11e6-87c5-04150e45265a.JPG)

Nu heb ik naar de data van deze user gekeken en ik zie een incorrect emailadres. Kan dat de reden zijn? Maar als deze error dan komt, moeten we niet stoppen :-) OF de user overslaan en doorgaan, OF de user gewoon opnemen met een foutief emailadres. Zie hier de ldap gegevens van deze user:

![error-inholland-2](https://cloud.githubusercontent.com/assets/1597455/23405153/44e80de4-fdb9-11e6-89f8-295193fbbfa7.JPG)

Kunnen we zien waar dit probleem zit en deze fixen?

**Comment by nicwortel** [comment]
@hermanvand er wordt inderdaad gevalideerd dat e-mailadressen ook daadwerkelijk voldoen aan het formaat van een e-mailadres. Dit gebeurt in de API, vandaar dat de applicatie een "400 Bad Request" status code terugkrijgt van de API.

Mij lijkt het wenselijk dat e-mailadressen altijd worden gevalideerd en dat waarden in het "e-mailadres" veld ook daadwerkelijk geldige e-mailadressen zijn (of de adressen daadwerkelijk bestaan is natuurlijk een ander verhaal, maar dat wordt hier niet gecontroleerd). In dat geval stel ik voor om het synchronisatiescript aan te passen, zodat de foutmelding wordt gelogd en het synchroniseren van de overige users vervolgens doorgaat.

Als jullie liever hebben dat users wel worden gesynchroniseerd, zelfs als ze een ongeldig "e-mailadres" hebben, dan kunnen we de validatie uitzetten en worden alle mogelijke waardes als e-mailadres geaccepteerd. Het risico hierbij is wel, dat als je later iets met dat e-mailadres wilt doen, er een heleboel ongeldige e-mailadressen in de data blijken te zitten.

**Comment by nicwortel** [comment]
@hermanvand en met betrekking tot het updaten van alle users: gebeurt dit eenmalig of worden alle users elke keer opnieuw geupdate?

Als dit eenmalig het geval is is dat waarschijnlijk omdat er nieuwe velden zijn toegevoegd / velden zijn aangepast. De data hiervoor staat nog niet in ons systeem dus moet eerst uit de LDAP worden gehaald.

Als de users elke keer opnieuw worden geupdate is er waarschijnlijk iets anders aan de hand. In dat geval stel ik voor om een nieuw ticket te openen.

**Comment by hermanvand** [comment]
Hoi Nic, 

wat betreft je eerste comment: je voorstel om een ongeldig emailadres niet toe te staan vind ik goed, dan hoeft de persoon dus niet gesynchroniseerd te worden. Belangrijk inderdaad is dat de overige personen vervolgens wel gesynchroniseerd worden.

wat betreft het 2e comment: De sync van users verloopt dagelijks. Users zouden geupdate moeten worden als er in de ldap iets is gewijzigd, wat nog niet in de grouphub api staat. Uit tests bij fontys blijkt nu dat ook als er niets gewijzigd is  in de ldap, de user in grouphub toch geupdate wordt. Dat kost onnodig veel tijd/resources. Hiervoor is een ticket door Frank al aangemaakt, zie #137 Ik zal dit ticket ook naar deze sprint verhuizen.

**Comment by hermanvand** [comment]
is gefixed, zie comment bij #137
