### ISSUE TITLE
Sortering van kolommen is stuk

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#132]
Na het kiezen van een andere kolom sortering is de kolom leeg en zijn er geen groepen meer te zien.

**Comment by hermanvand** [comment]
alleen sortering van de groene kolom werkt nog niet

**Comment by hermanvand** [comment]
Dit is een lastiger probleem dan verwacht. De sortering van de groene kolom loopt mee met de sortering van de blauwe kolom... Dus als blauw gesorteerd wordt op a-z, dan wordt daarna groen ook gesorteerd op a-z ongeacht welke sortering je kiest op de groene kolom.

De data van beide kolommen wordt met 1 api call opgehaald. Daar heeft het mee te maken, maar dat was waarschijnlijk gedaan vanuit performance oogpunt.

anyway, voor nu lijkt het beter om de sortering weg te halen. Mijjn vorostel is om 
- geen sortering te hebben op de blauwe en groene kolom, omdat we daar niet 10-tallen groepen verwachten
- wel sortering op de paarse en grijze kolom, want die bevatten potentieel alle groepen.

later als er verder gewerkt wordt aan de grouphub code, dan moeten we deze sortering ook weer oppakken.

**Comment by mdeletter** [comment]
Fixed, zie: https://github.com/SURFnet/grouphub/commit/f00cab97c0e9fa73a872c996bbe5c41e40580f3b
