### ISSUE TITLE
De kolom alle groepen laat alleen de eerste 12 groepen zien.

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#133]
De kolom alle groepen laat alleen de eerste 12 groepen zien. Daarna stop het. Ook de knop more mist.

**Comment by mdeletter** [comment]
De kolom 'alle groepen' gebruikt endless-scrolling om alle groepen in de lijst weer te geven.
Dit in tegenstelling tot de kolom 'Organisatie groepen' die een knop 'more' gebruikt om meer groepen in te laden.

Getest met de laatste versie (83c9e3a) waarbij de endless scroll functionaliteit prima werkt.
Graag nogmaals testen.

**Comment by hermanvand** [comment]
Ik heb hier niet consistent gedrag geconstateerd.

wat betreft endless scrolling:
Na inlezen van de users en groepen uit de ldap werkte endess-scrolling op de paarse kolom goed.
Vervolgens ging ik de fix voor dit issue testen door het aanmaken van 15 groepen. Binnen de kolom alle groepen ging endless scrolling toen fout. Waarna ook endless scroling fout gaat bij alle kolommen. Daar komt nu helemaal niets meer bij....

![afbeelding](https://user-images.githubusercontent.com/1597455/31610536-b1d33dce-b278-11e7-98e5-1987eddcd85d.png)

wat betreft de 'more' knop:
Het klopt dat die alleen maar in de blauwe en groene kolom wordt gebruikt. 
Deze knop werkt echter niet, vanaf het begin af aan al niet, het radartje blijft draaien...

![afbeelding](https://user-images.githubusercontent.com/1597455/31610581-d7f6202a-b278-11e7-848b-d1cfdb62f4d5.png)

**Comment by hermanvand** [comment]
het lazy loading probleem is met de nieuwe api opgelost. Daarom sluit ik dit issue. Het ' more' knopje blijft maar dat is al beschreven.
