### ISSUE TITLE
Add groups tabblad zoekfunctie werkt niet goed

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#134]
De zoekfunctie in het tabblad Add Groups werkt niet goed. Zoekquery's leveren verkeerde resultaten op.

**Comment by hermanvand** [comment]
dit is nog steeds niet het geval, zie:

![afbeelding](https://user-images.githubusercontent.com/1597455/31610778-a60d0a0a-b279-11e7-9bb0-afbdf88b37c8.png)

**Comment by hermanvand** [comment]
fixed met nieuwe api
