### ISSUE TITLE
Group Members indicator wordt niet bijgewerkt bij het kopiëren van groepsleden

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#136]
Bij het kopiëren van groepsleden uit een bestaande groep via het tabblad add members> zoeken op groups. Wordt de teller bij Group members (x) niet bijgewerkt. Als je vervolgens het tabblad group members aanklikt zijn de betreffende members ook niet in de lijst te zien.

Pas bij het sluiten en weer openen van het scherm zijn de nieuwe members te zien.

**Comment by Frankniesten** [comment]
Bij het kopiëren verhoogd wel de teller bij Group in Groep met 1. Deze zou op nul moeten blijven staan bij het kopiëren van alleen leden naar de huidige group.

**Comment by hermanvand** [comment]
Dit is gefixed. Alleen gaat er nog iets anders mis.

als ik een groep toevoeg bij 'add group', dan komt de teller netjes op 1.
Maar als ik dan besluit om in hetzelfde window de groep weer weg te halen, dan komt de teller op '-1', dat moet '0' zijn uiteraard.

na toevoegen

![afbeelding](https://user-images.githubusercontent.com/1597455/31610902-44886260-b27a-11e7-9565-01623df58e9a.png)

na verwijderen

![afbeelding](https://user-images.githubusercontent.com/1597455/31610963-6bbe0402-b27a-11e7-80c8-ca5efee7baba.png)

**Comment by mdeletter** [comment]
Gefixed in e4f2889b74b885bb57c04f9e2ecc9ae4b18f25f8
Graag nogmaals testen op de test omgeving met deze nieuwe versie

**Comment by hermanvand** [comment]
Er vanuit gaande dat grouphub.js wordt geupdate als ik ' cache:clear'  doe, zodat de wijzigingen in scripts.js meegenomen worden. Dan zie ik dit probleem nog steeds in de interface, zie screenshot

en daarbij is een ander probleem geintroduceerd met een lege avatar. Als je een member toevoegd, dan komt er een leeg vakje voor zijn naam in  'group members', zie screenshot. Als je nu de dialoog sluit en weer opent, dan is dat vakje weg. Dit inspringen ziet er een beetje raar uit. Liefst altijd een leeg vakje, dus ook bij Adam Bos, in dit voorbeeld. Dan lijnt het altijd goed uit, ook als er wel avatars zijn.

![image](https://user-images.githubusercontent.com/1597455/31770941-67ac9d9e-b4da-11e7-87df-6a1e8cab3767.png)
