### ISSUE TITLE
LDAP Sync - Members worden bij iedere run allemaal geüpdate

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#137]
Bij het syncen van de LDAP worden bij iedere run alle users voorzien van een update. Ook als er niets gewijzigd is. Hierdoor duurt de sync extreem lang.

**Comment by hermanvand** [comment]
Het lijkt er op dat in de file Service/SynService, op regel 94, de synchronize() functie niet de juiste index teruggeeft.
        
`$index = $grouphubUsers->synchronize($ldapUsers, true);`

Als ik nl. het eerste element van $ldapUsers en $grouphubUser print met:
        
```
print_r($ldapUsers[0]);
print_r($grouphubUsers[0]);
```

Dan zie je dat het element wel gelijk is, maar toch zie je daarna het element toegevoegd worden, zie de output van het proces:

Merk op dat: de user uit de ldap lijst geen id heeft.

```
> root@05cb0e1c34d6:/var/www/grouphub/current/src/AppBundle# /var/www/grouphub/current/bin/console grouphub:sync -e=prod --type=users -vvv
> [2017-10-16 13:33:58] app.INFO: Processing users 0 to 5000...  
> AppBundle\Model\User Object
> (
>     [id:AppBundle\Model\User:private] => 
>     [reference:AppBundle\Model\User:private] => cn=Adam Bakker,ou=Users,ou=FPLO,dc=surfuni,dc=org
>     [firstName:AppBundle\Model\User:private] => Adam
>     [lastName:AppBundle\Model\User:private] => Bakker
>     [displayName:AppBundle\Model\User:private] => 
>     [loginName:AppBundle\Model\User:private] => Adam.Bakker
>     [emailAddress:AppBundle\Model\User:private] => Adam.Bakker@student.surfuni.org
>     [avatarUrl:AppBundle\Model\User:private] => 
>     [extraAttributes:AppBundle\Model\User:private] => Array
>         (
>         )
> 
> )
> AppBundle\Model\User Object
> (
>     [id:AppBundle\Model\User:private] => 1
>     [reference:AppBundle\Model\User:private] => cn=Adam Bakker,ou=Users,ou=FPLO,dc=surfuni,dc=org
>     [firstName:AppBundle\Model\User:private] => Adam
>     [lastName:AppBundle\Model\User:private] => Bakker
>     [displayName:AppBundle\Model\User:private] => 
>     [loginName:AppBundle\Model\User:private] => Adam.Bakker
>     [emailAddress:AppBundle\Model\User:private] => Adam.Bakker@student.surfuni.org
>     [avatarUrl:AppBundle\Model\User:private] => 
>     [extraAttributes:AppBundle\Model\User:private] => Array
>         (
>         )
> 
> )
> [2017-10-16 13:34:08] app.INFO:  - Going to add 0 users to Grouphub...  
> [2017-10-16 13:34:08] app.INFO:  - Going to update 4950 users in Grouphub...  
> [2017-10-16 13:34:08] app.INFO:  -- Updating cn=Adam Bakker,ou=Users,ou=FPLO,dc=surfuni,dc=org  
> [2017-10-16 13:34:08] app.INFO:  -- Updating cn=Adam Blom,ou=Users,ou=FPLO,dc=surfuni,dc=org  
> [2017-10-16 13:34:08] app.INFO:  -- Updating cn=Adam Bos,ou=Users,ou=FPLO,dc=surfuni,dc=org  
> ...
```

**Comment by hermanvand** [comment]
Ja, dit werkt. Als ik nu een update doe met twee wijzigingen erin.

Adam Kok => Adam Cock
Adam.deHaan@student.surfuni.org => Adam.deHaan.met.een.ongeldig.email.adres

Dan is dit de goede output:

/var/www/grouphub/current/bin/console grouphub:sync -e=prod --type=users -vvv
[2017-10-19 12:20:40] app.INFO: Processing users 0 to 5000...  
[2017-10-19 12:20:50] app.INFO:  - Going to add 0 users to Grouphub...  
[2017-10-19 12:20:50] app.INFO:  - Going to update 2 users in Grouphub...  
[2017-10-19 12:20:50] app.INFO:  -- Updating cn=Adam de Haan,ou=Users,ou=FPLO,dc=surfuni,dc=org  
[2017-10-19 12:20:50] app.ERROR:  -- Validation failed for user cn=Adam de Haan,ou=Users,ou=FPLO,dc=surfuni,dc=org  
[2017-10-19 12:20:50] app.INFO:  -- Updating cn=Adam Kok,ou=Users,ou=FPLO,dc=surfuni,dc=org  
[2017-10-19 12:20:51] app.INFO:  - Going to remove 0 users from Grouphub...  
[2017-10-19 12:20:51] app.INFO: Processing users 4950 to 9950...  
[2017-10-19 12:20:53] app.INFO: Done syncing users!
