### ISSUE TITLE
Meer functionaliteit in 'Mijn groepen' is stuk

### ISSUE THREAD

**Issue by mdeletter** [SURFnet/grouphub#142]
Na het klikken op 1 van de 'meer' links in de 'mijn groepen' lijst wordt er een wel een spinner getoond, maar wordt het resultaat niet verder uitgebreid.

**Comment by hermanvand** [comment]
ja, dat had ik ook geconstateerd bij #133

**Comment by hermanvand** [comment]
opgelost
