### ISSUE TITLE
Inactieve groepen

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#18]
Verwijderde groepen die als bron de LDAP hebben worden inactive gezet. Als er vervolgens een sync plaatsvindt waarbij ze weer nieuw worden aangemaakt lukt dit niet omdat de Group reeds bestaat in de Database. De GroupHub API geeft vervolgens een 400 error.

**Comment by Frankniesten** [comment]
LDAP groepen in groupHUB moeten als ze niet meer bestaan in de LDAP helemaal worden verwijderd uit de groupHUB database en niet op inactive worden gezet. Dit om latere sync problemen te voorkomen. 

De inactive status geld dus alleen voor eigen groupHUB groepen.

**Comment by Tjeerd** [comment]
Fixed in https://github.com/SURFnet/grouphub.api/commit/76facb386c0a4c5348a8b79c2f30db305cc9ff1d

**Comment by Frankniesten** [comment]
Dit lijkt nog steeds een issue te zijn.

**Comment by Frankniesten** [comment]
Dit lijkt nog steeds een issue te zijn.

**Comment by Frankniesten** [comment]
Probleem zat hem erin dat er nog LDAP groepen op inactief stonden. Deze waren op inactief gezet voordat bovenstaande bug fix is gereleased. Blijkbaar liepen we nu tegen het conflict aan dat toevallig dezelde groep weer werdt aangemaakt.
