### ISSUE TITLE
Status van Dropdown menu's in GUI wordt niet onthouden bij refresh van browser

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#22]
- [ ] De status in- of uitgeklapt van de  dropdown menu's Owner, Administrator en member worden niet onthouden. Als de pagina inhoud om de x aantal minuten wordt ververst klapt een menu dat is verborgen automatisch weer uit.

**Comment by Frankniesten** [comment]
De sortering is ook opgeslagen in de cookie.

**Comment by lucasvanlierop** [comment]
Gefixt door: https://github.com/SURFnet/grouphub/pull/87
