### ISSUE TITLE
Een 'managedby' attribuut waarin staat wie een grouphub groep heeft gemaakt

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/grouphub#24]
oplossing: Net als het configuratie element 'accountname' waar een waarde achter kan komen waar de cn in word gezet een element 'owner' waar een waarde in kan komen waar de eigenaar wordt ingezet. (de waarde is in geval van inholland dan managedby).

**Comment by Frankniesten** [comment]
Dit is zelfde issue als: #31

**Comment by Frankniesten** [comment]
Naast de Owner ook de huidige naam (displayname) meegeven in een part veld.

**Comment by Tjeerd** [comment]
Welke waarde van de owner user is gewenst in dit te-mappen `owner` veld?

Ik heb voor nu de `reference`, dus de `dn`gekozen.
