### ISSUE TITLE
Alle Grouphub groupen komen altijd in aanmerking voor een update

### ISSUE THREAD

**Issue by Tjeerd** [SURFnet/grouphub#34]
Reden hiervoor is dat de 'name' (CN) altijd gewijzigd lijkt  te zijn.

**Comment by lucasvanlierop** [comment]
I noticed this when debugging this line: https://github.com/SURFnet/grouphub/blob/master/src/AppBundle/Service/SyncService.php#L308

![reason-groups-keep-updating](https://cloud.githubusercontent.com/assets/1073227/20562916/7461ed30-b186-11e6-8564-200c12bb845f.png)

**Comment by Frankniesten** [comment]
Deze admin groep wordt aangemaakt bij installatie. De admin is vervolgens in staat om admingroepen aan te maken. Als je als gebruiker lid bent van zo'n admin Group ben je in staat om semi-formele (groene) groepen aan te maken.

**Comment by lucasvanlierop** [comment]
Ik bedoel meer dat je hier goed ziet wat er verandert, het is bij alle groepen zo:

![another-group-which-must-be-synced-everytime](https://cloud.githubusercontent.com/assets/1073227/20563827/82f67fec-b18a-11e6-84cd-2817395c7d02.png)

**Comment by lucasvanlierop** [comment]
@Frankniesten nu ik er toch tegenaan liep ben ik even aan het kijken, die `name` zou dat in dit geval `TEST_2` of `TEST` moeten zijn? Anders gezegd staat het initieel goed en probeert ie het verkeerd aan te passen of andersom?

**Comment by Frankniesten** [comment]
Ben hier niet helemaal in thuis. Herman weet hier meer van maar hij is deze week afwezig. Ik doe een poging zo ver dat ik er vanaf weet.

De naam van de Group is TEST. De _2 is het group id wat we meegeven om de Group te kunnen herkennen indien de naam van de Group daarna ooit aangepast wordt.

Dus de reference krijgt _2 erbij en de name als ik me niet vergis niet. Name kan vervolgens als displayname gebruikt worden. 

Als de naam van een groep wordt aangepast zal de reference hetzelfde blijven omdat er anders een nieuwe groep lijkt te ontstaan waardoor afnemende systemen in de war kunnen raken. Dus TEST_2 blijft ten alle tijden zo staan. 

Wat ook kan meespelen bij dit issue is dat de reference wordt afgekapt omdat er maar maximaal 64 tekens bij dit attribuut in de AD passen. Het afkappen kan er vervolgens voor zorgen dat hij opnieuw gaat updaten. 

Misschien is het goed om Tjeerd even te benaderen hoe dit precies zit. Hij heeft dit issue immers ook ingeschoten. Was meer voor hemzelf dat dit opgelost moest worden.

**Comment by Tjeerd** [comment]
Inderdaad zoals @Frankniesten al aangeeft, op het moment dat wij een group naar de LDAP syncen voorzien we de CN van een postfix om zo de id te kunnen herkennen. Echter wordt die CN later ook op het name attribute van de Group gemapped mocht er geen expliciete displayName geconfigureerd zijn. Hierdoor lijkt de name van de group in Grouphub dus altijd gewijzigd tov de name van de group in LDAP.

Dit is dus alleen een inefficientie welke optreedt wanneer er geen expliciete displayName attrib geconfigureerd is. @Frankniesten hoe zijn de huidige omgevingen geconfigureerd? Is dit niet alleen aan de hand op de testomgeving (surfuni)? Zo ja, dan moeten we de displayName attrib misschien verplicht maken en ook op de testomgeving inrichten/configureren?

**Comment by Tjeerd** [comment]
Andere mogelijkheid is dat we op de een of andere manier misschien die postfix er weer af kunnen strippen?

**Comment by lucasvanlierop** [comment]
Net even met @Tjeerd overlegd wat hem betreft is de prio niet super hoog dus ik heb mijn aanpassingen even gepushed, we kunnen later even checken in hoeverre deze klopt: 
https://github.com/SURFnet/grouphub/pull/64/files

**Comment by lucasvanlierop** [comment]
Het valt mij op dat name helemaal niet gesynced wordt naar Ldap omdat deze niet aanstaat in de mapping configuratie:
![name-non-mapped](https://cloud.githubusercontent.com/assets/1073227/20750546/bff1af30-b6f7-11e6-825a-16bb85df8994.png)

FYI als ik deze aanzet krijg ik een LDAP error:
```
[Symfony\Component\Ldap\Exception\LdapException]  
Object class violation
```

**Comment by hermanvand** [comment]
name wordt wel gesynced, daar komt standaard NAAM_ID in terecht.

de 'name' die hier in de configuratie staat heeft andere doeleinden. Die moet je andersom lezen. Als hier iemand bijvoorbeeld name:displayname invult, dan wordt in het atrribuut 'displayname' de originele NAAM weggeschreven.

btw: hetzelfde geldt voor accountName & owner, daar kunnen ook attributen voor worden gespecificeerd waar vaste waarden in komen.

**Comment by lucasvanlierop** [comment]
Na overleg opgelost door alleen eigenschappen van groupen ter vergelijken die ook daadwerkelijk in de LDAP server kunnen worden opgeslagen. Dit is te configureren d.m.v. de mapping parameters:

Zie: https://github.com/SURFnet/grouphub/pull/64
