### ISSUE TITLE
Lange groepsnamen worden in de UI niet afgekapt.

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#35]
Lange groepsnamen worden in de UI niet afgekapt. Hierdoor wordt de kolom breder en krijg je een horizontale scroll balk.

**Comment by lucasvanlierop** [comment]
Zie: https://github.com/SURFnet/grouphub/pull/67/files

**Comment by Frankniesten** [comment]
Groepnaam die te lang is afkappen zodat er maar 1 regel gebruikt wordt.

Dit geld voor zowel groepnamen met spaties als groeizaam met heel veel karakters.

**Comment by lucasvanlierop** [comment]
@Frankniesten Alle lange groepsnamen worden nu afgekapt en weergegeven met `...` aan het einde, zie:
https://github.com/SURFnet/grouphub/pull/80
