### ISSUE TITLE
Ontsluiten van de juiste (meer) persoonsgegevens om People Picker beter te laten functioneren.

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#40]
Om zeker te weten dat je de juiste persoon selecteert is het fijn om meer gegevens van personen te zien.
- Attibute Displayname gebruiken in plaats van voor- achternaam.
- Instituut/ afdeling
- Studentnr
- Avatar

Randvragen:
- Wie mag dit zien. 
- Is dit de eigenaar/ admin van de groep.
- Alle leden van de groep.
- Iedereen
- Medewerkers vs studenten

**LET OP: Hier is privacy belangrijk misschien moet dit daarom configureerbaar maken. Dit geld voor zowel de people picker als voor het inzien van leden van bijv. formele groepen**

**Comment by hermanvand** [comment]
btw: Extra velden die we uit de ad halen moeten configureerbaar worden

**Comment by nicwortel** [comment]
Display name en avatar standaard tonen
Extra (configureerbare) velden onder een uitklap knopje
