### ISSUE TITLE
Gebruikersnaam rechtsboven is de helft van je inlog

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#44]
Hiervoor wellicht displayname attribute gebruiken

**Comment by Tjeerd** [comment]
Als dit security gerelateerd zou zijn, dan is dit niet echt een issue. De username is nl. geen secret, dat is alleen het password. De username wordt bijvoorbeeld ook gebruikt in URL's e.d. Vergelijk het met het inloggen met een email adres, ook deze is niet 'geheim' (zoals bijv bij Google, Facebook e.d.).

**Comment by Frankniesten** [comment]
Hiervoor displayname gebruiken. Deze slaan we nu echter niet op. Maar dit gaan we wel doen zoals is aangegeven in issue #40

**Comment by nicwortel** [comment]
Fixed by #97

**Comment by nicwortel** [comment]
UID als er geen display name is
