### ISSUE TITLE
Groepen waar je alleen owner van bent worden meegestuurd via VOOT

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#49]
het voot endpoint moet niet alleen groepen waar je owner van bent terug sturen, maar ook diegene waar je member of administrator van bent.

**Comment by lucasvanlierop** [comment]
Ik krijg zowel admin, member als owner te zien, doe ik iets verkeerd of is het probleem al opgelost?

![voot-result](https://cloud.githubusercontent.com/assets/1073227/20670351/c498b55e-b578-11e6-89f1-efce095e0c73.png)

**Comment by Frankniesten** [comment]
Alle rollen worden goed doorgegeven. Alleen prospect mag niet doorgegeven worden. Dit gebeurd nu wel.

**Comment by lucasvanlierop** [comment]
Prospect filter toegevoegd: https://github.com/SURFnet/grouphub/pull/70/files

**Comment by Frankniesten** [comment]
Hier is nog een kleine aanpassing nodig: Naast groepen waar je prospect van bent mogen ook groepen waar je owner bent niet doorgegeven worden richting de VOOT API.

Dus alleen groepen waar je Admin of member van bent. gaan richting API.

**Comment by lucasvanlierop** [comment]
@Frankniesten Gefixt door: https://github.com/SURFnet/grouphub/pull/79/files
