### ISSUE TITLE
Filter voor het sorteren van groepen wijzigt niet altijd

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#50]
Als je de filter op dec - jan wijzigt veranderd dit niet mee in de UI.

**Comment by Tjeerd** [comment]
Het descending/ascending icoontje wijzigt wel, maar dit blijkt dus niet duidelijk genoeg.

**Comment by Frankniesten** [comment]
Dit werkt gewoon naar behoren
