### ISSUE TITLE
Prospects gaan mee naar de AD

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#51]
Leden met de status prospect worden meteen mee-gesynced richting AD. Dit mag niet omdat deze nog niet de formele lidmaatschaps status hebben. De owner of admin moet dit nog goedkeuren.

**Comment by Tjeerd** [comment]
@lucasvanlierop: Users hebben een bepaalde rol binnen een Group, ze zijn admin, member of prospect. Wanneer gebruikers van een group gesynced worden naar LDAP wordt, vooralsnog, met deze rol geen rekening gehouden (het concept van een rol bestaat alleen binnen Grouphub).

De vraag hier is nu om de alleen de users met de rol admin en member te syncen.

De call naar de api zal hiervoor aangepast moeten worden zodat alleen die users teruggegeven worden of de users moeten er aan de consumer kant handmatig gefiltered worden. Er bestaan al mogelijkheden om te filteren op de API dus wellicht is het een kwestie van de parameters aan te passen.
