### ISSUE TITLE
Zoekfunctie uitbreiden met Groeps Query

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#54]
- [X] In het zoekveld een query kunnen doen op groepen. Vervolgens kun je met een klik alle leden van een groep toevoegen aan een nieuwe groep. Dit is een copy en geen groep in groep.

Mogelijke uitbreidingen van de zoekfunctionaliteit:
- [x] Automatisch in naam **en** email zoeken.
- [x] group: [GROEPSNAAM]
- [x] email: [EMAIL], [EMAIL2], [EMAIL3] **(N.B. er wordt gezocht op alle email adressen)**
- [x] student: [STUDENTNR], [STUDENTNR2], [STUDENTNR3] Afhankelijk van #40 

- [x] In het zoekvenster (add members) waar je members of groepen kunt toevoegen zou het fijn zijn dat als je de optie groepen selecteert je daaronder de eerste x aantal groepen ziet. Net zoals dat nu bij users het geval is. Dus afhankelijk van je keuze moeten er users of groepen zichtbaar zijn.

- [x] De feedback van het toevoegen zit hem bij users in het tonen van het dropdownmenu meteen nadat je een gebruiker hebt toegevoegd. Daarmee kun je vervolgens de rol van de personen kunt instellen. Dit zou ook voor groepen moeten gelden.

- [x] Bij het toevoegen van nieuwe members wordt meteen het tabblad Groupmembers geüpdate. Op het moment dat je vanuit het tabblad add members terug klikt naar groupmembers zijn de nieuwe leden meteen zichtbaar. Bij het toevoegen van groepen is dit nu niet het geval. Dit is wel wenselijk omdat het nu lijkt dat het toevoegen mislukt is.

- [x] De applicatie is nu twee-talig. We moeten dit ook in de radio buttons doorvoeren.

- [x] Is het eventueel mogelijk om de radiobuttons in de zoekbalk te stylen. Zie voor een voorbeeld het screenshot in de bijlage zoals linkedin dit bijvoorbeeld doet.
<img width="242" alt="mail-bijlage" src="https://cloud.githubusercontent.com/assets/2547879/20525909/eba8b9c0-b0c1-11e6-81b5-3655949423a2.png">

**Comment by Tjeerd** [comment]
Radio optie maken voor zoeken in OF groepen OF users. Vervolgens zoeken binnen attributen naam, email, studentnr etc

**Comment by Frankniesten** [comment]
Als ik een groep kopieer met meer dan 100 leden worden alleen de eerst 100 gekopieerd daarna is het klaar en stopt het proces.
