### ISSUE TITLE
Exporteren verbeteren

### ISSUE THREAD

**Issue by Frankniesten** [SURFnet/grouphub#58]
- Bij het exporteren van groepen naar CSV. De CSV file noemen naar de groepsnaam + ID + Datum.

**Comment by lucasvanlierop** [comment]
Zit hier: https://github.com/SURFnet/grouphub/blob/master/src/AppBundle/Controller/GroupController.php#L245

**Comment by DRvanR** [comment]
Updated location: https://github.com/SURFnet/grouphub/blob/c8697293938cd699678112233fac6e06c04e7371/src/AppBundle/Controller/GroupController.php#L292

**Comment by nicwortel** [comment]
@Frankniesten ik heb de aannames gedaan dat je met datum de huidige datum bedoelt (de datum waarop het bestand wordt gedownload), dat er een underscore (`_`) als scheidingsteken tussen de naam, ID en datum kan worden gebruikt, en ik heb de datum in JJJJ-MM-DD notatie gebruikt zodat meerdere exports van een zelfde groep automatisch worden gesorteerd op datum.
