### ISSUE TITLE
Groep toevoegen aan een nieuwe groep

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/grouphub#7]
Bestaande groep toevoegen aan een nieuwe groep.

**Comment by hermanvand** [comment]
Alleen werkend maken voor semi-formele groepen en maar één (1) niveau diep

dus wel:
groep a is formele groep.
groep b is formele groep
groep c is semi-formele groep met daarin a
groep d is semi-formele groep met daarin a EN b

dus niet:
groep e is semi-formele groep met daarin c

**Comment by Frankniesten** [comment]
Hier een opzet voor de ui:

![ui issue 7](https://cloud.githubusercontent.com/assets/2547879/20309146/284b341e-ab47-11e6-8d7a-19b9411c4302.png)

**Comment by lucasvanlierop** [comment]
Dit is vrij complex issue wat uit vele subtaken bestaat, onderstaand een overzicht van de subtaken die ik geidentificeerd heb en de status daar van:

- [x] Extra tab toevoegen om groepen te linken
- [x] In de toevoeg tab alleen bepaalde typen groepen tonen
- [x] In de toevoeg tab alleen groepen zonder subgroepen tonen
- [ ] In de toevoeg tab alleen nog niet gelinkte groepen tonen
- [x] In de toevoeg tab groep linken aan groep
- [x] Extra tab toevoegen om gelinkte groepen te tonen
- [ ] In de gelinkte groepen tab automatisch groepen toevoegen na linken
- [x] In de gelinkte groepen tab groep verwijderen uit groep

Zie: 
https://github.com/SURFnet/grouphub/pull/89/files
https://github.com/SURFnet/grouphub.api/pull/5/files

**Comment by hermanvand** [comment]
test resultaten 2feb

- bij aanmaken nieuwe groep is submit button niet mooi meer
- ik kan ook ad-hoc groep in groep maken (was dat nou de bedoeling of niet? Laat maar even zo.)
- na toevoegen groep gaat de groep netjes naar de nieuwe tab 'group in group', maar na verwijderen groep gaat hij NIET terug naar de tab 'add groups'
- na toevoegen lege groep worden er een willekeurig aantal members opgeteld in de tab 'group members (10)', dat moet gewoon 0 blijven. Na opnieuw starten groep is aantal wel weer 0
- na toevoegen van een groep (A) in een andere groep (C) kan ik niet nogmaals groep A toevoegen aan een andere groep. Dat zou wel moeten mogen. Je mag niet groep C toe gaan voegen. Dat klopt wel.
- In groep A heb ik een member zitten, in groep C heb ik groep A toegevoegd. Daar zie ik niet nu de members. Dit lijkt raar, maar is wel goed.
- net als bij 'group member (1)' moeten we ook bij 'group in group (1)' een aantal kunnen zien om de status weer te geven. Dan is het onderscheidt duidelijker tussen de tab 'group in group' en 'add groups'.
- ik zie de nieuwe groepen niet verschijnen in de ldap op de testomgeving, wordt die niet meer gesynced? Nee dus, zie:

updaten ldap:

root@grouphub:/var/www/grouphub/current/app/config# /var/www/grouphub/current/bin/console grouphub:sync --type=grouphub -e=prod
PHP Fatal error:  Class AppBundle\Ldap\LdapClient contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Ldap\LdapInterface::query, Symfony\Component\Ldap\LdapInterface::getEntryManager) in /var/www/grouphub/releases/20170131151641/src/AppBundle/Ldap/LdapClient.php on line 371
                                                                                                                                                                                                                                      
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                                             
  Error: Class AppBundle\Ldap\LdapClient contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Ldap\LdapInterface::query, Symfony\Component\Ldap\LdapInterface::  
  getEntryManager)                                                                                                                                                                                                             
                                                                                                                                                                                                                                     
grouphub:sync [--type TYPE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by nicwortel** [comment]
@hermanvand ik heb alle resultaten uit [jouw comment](https://github.com/SURFnet/grouphub/issues/7#issuecomment-276952445) (behalve de zaken waarvan jij hebt gezegd dat ze zo goed zijn) opgesplitst in losse issues. Om die reden ga ik dit issue sluiten.
