### ISSUE TITLE
Naam wordt inc. Id suffix wordt getoond in UI

### ISSUE THREAD

**Issue by lucasvanlierop** [SURFnet/grouphub#75]
Deze zou gestript moeten zijn.

**Comment by Frankniesten** [comment]
Als je dit bedoeld is dit met voorbedachte rade en is dit geen issue:

<img width="862" alt="schermafbeelding 2016-12-08 om 13 39 32" src="https://cloud.githubusercontent.com/assets/2547879/21010345/d96da9d2-bd4b-11e6-859c-a6f11a3f1c3d.png">

**Comment by lucasvanlierop** [comment]
Ok toch wel, probleem is nu in ieder geval dat ie er nog een keer achter geplakt wordt.
![dubbel_groep_id](https://cloud.githubusercontent.com/assets/1073227/21010645/7eeb27e4-bd4d-11e6-87e5-2a73ef32efde.png)

**Comment by Frankniesten** [comment]
Inderdaad ik zie het nu ook.

**Comment by lucasvanlierop** [comment]
Gefixt door: https://github.com/SURFnet/grouphub/pull/77

**Comment by lucasvanlierop** [comment]
Ter info de naam wordt zonder `{ID}` suffix opgeslagen in de GroupHub database en inclusief die suffix naar de CN geschreven bij het aanmaken. Verder wordt niet langer meer de CN als naam gebruikt vanuit LDAP -> GroupHub maar de gemapte `name` indien geconfigureerd.
